レシピ機能の追加をしました。
Tohya-Kuribayashi/Cookpad pull request #2
Opened 2021-05-06 23:52 UTC by Tohya-Kuribayashi

レシピ機能を追加いたしました。現在、レシピを編集する画面を作成中です。作成が終わり次第、このブランチにpushしたいと思います。

2021-05-06 23:59 UTC, Tohya-Kuribayashi commented on app/controllers/recipes_controller.rb
> +  end
ここはまだ作成途中です。

2021-05-06 23:59 UTC, Tohya-Kuribayashi commented on app/models/recipe.rb
> +  validates :description, presence: true, on: :update
現在、画像とタイトルを入力した後に一度saveメソッドで保存をし、できたものをupdateメソッドで編集していくという仕様になっています。そのため、updateメソッドの時にdescriptionを入力するので、on:を使ってエラーが起こるのを防ぎました。

2021-05-06 23:59 UTC, Tohya-Kuribayashi commented on app/views/recipes/index.html.erb
> +</div>
これは、pictgramの写真投稿を参考に作ったので、投稿したものの一覧ページになっています。ここに材料や手順の編集を追加する予定です。

2021-05-07 00:26 UTC, bishantakuma-abewadana requested changes
`.gitignore`に`/public/uploads`を追加してください。
レシピの詳細、削除機能も作成してください。

2021-05-07 00:26 UTC, bishantakuma-abewadana commented on app/controllers/recipes_controller.rb
> +end
改行を入れてください
https://qiita.com/lemtosh469/items/b3a5b3b40d9f44dfbd06

2021-05-07 00:26 UTC, bishantakuma-abewadana commented on app/controllers/recipes_controller.rb
> +
showアクションも作ってください。

2021-05-07 00:26 UTC, bishantakuma-abewadana commented on app/models/recipe.rb
> +  validates :description, presence: true, on: :update
口頭で説明しましたが、登録画面でdescriptionも入力できるようにしてください。
```suggestion
  validates :description, presence: true
```

2021-05-07 00:26 UTC, bishantakuma-abewadana commented on app/views/recipes/index.html.erb
> +</div>
まずは詳細ページを作ってそこに材料や手順の登録・編集・削除ボタンを追加してください。

2021-05-07 00:26 UTC, bishantakuma-abewadana commented on app/views/recipes/new.html.erb
> +
入力する項目にdescriptionも追加してください。

2021-05-07 00:26 UTC, bishantakuma-abewadana commented on config/routes.rb
> +  get 'recipes/new'
`  resources :recipes` でnew作成されるので不要です

2021-05-12 12:56 UTC, Tohya-Kuribayashi reviewed
レシピ機能で不足していたものを追加しました。

2021-05-12 12:56 UTC, Tohya-Kuribayashi commented on app/controllers/recipes_controller.rb
> +
レシピの詳細画面を作成しました。

2021-05-12 12:56 UTC, Tohya-Kuribayashi commented on app/views/recipes/show.html.erb
> +</div>
レシピの一覧ページからフォームを借りて作成しました。ユーザー名、料理名、料理の画像、料理の説明の4つが出力されています。その4つの下に、手順と材料が追加できるボタンをそれぞれ作成しました。ボタンのフォームは既に作成したものを使いました。ボタンのリンク先が "#" になっていますが、それぞれ 'new_process_path' と 'new_material_path' に変更する予定です。

2021-05-12 12:59 UTC, Tohya-Kuribayashi reviewed
gitignoreに/public/uploadsを追記しました。

2021-05-12 12:59 UTC, Tohya-Kuribayashi commented on .gitignore
> +/public/uploads
メンタリング時にご指摘があったものを追記しました。

2021-05-13 15:16 UTC, Tohya-Kuribayashi reviewed
レシピに手順を加える機能を追加しました。
Processという名前で作る予定でしたが、Ruby_on_Railsの中で「Process」が他の名前に使用されているというエラーが出たので、Stepという名前に変更しました。

レシピ投稿と手順の追加の２つについて、投稿機能は付けたのですが、編集・削除の２つの機能をまだ付けておりません。

2021-05-14 00:55 UTC, belion-freee approved these changes
問題ありません

2021-05-14 00:55 UTC, belion-freee commented on config/routes.rb
> +  resources :steps
### nits
対応は不要ですが、recipesにネストして作ると綺麗なroutingになります

2021-05-14 05:08 UTC, merged